### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ghost** [qzwlecr/netease-cloud-music-docker-version#3]
:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                                 [################################] 100%
(1/1) 正在检查软件包完整性                                   [################################] 100%
(1/1) 正在加载软件包文件                                     [################################] 100%
(1/1) 正在检查文件冲突                                       [################################] 100%
(1/1) 正在检查可用硬盘空间                                   [################################] 100%
:: 正在处理软件包的变化...
(1/1) 正在重新安装 netease-cloud-music-docker-version        [################################] 100%
Using default tag: latest
latest: Pulling from qzwlecr/netease-cloud-music-docker-version
ae79f2514705: Pulling fs layer
5ad56d5fc149: Pulling fs layer
170e558760e8: Pulling fs layer
395460e233f5: Pulling fs layer
6f01dc62e444: Pulling fs layer
1b5bc6de68e6: Pulling fs layer
6f01dc62e444: Waiting
5ad56d5fc149: Verifying Checksum
5ad56d5fc149: Download complete
170e558760e8: Download complete
6f01dc62e444: Download complete
395460e233f5: Download complete
卡在这一步

**Comment by qzwlecr** [comment]
In some shells, .install script can't show its download speed.And you can exec `docker pull qzwlecr/netease-cloud-music` manually , after you can access docker daemon.
As download speed from docker hub may be slow, you can use some network accelerators, for example, daocloud, etc.
